#+TITLE: Math as Divinely Inspired
#+DATE: <2021-11-14 Sun>
#+AUTHOR: Salvador Guzmán
#+EMAIL: guzmansalv@gmail.com
#+OPTIONS: text:t
#+CATEGORY: Math
#+CATEGORY: Deconstruction
#+LANGUAGE: en

* Introduction
The extraordinary purchase that the intellectual blossoming mathematics
experienced is beyond reproach. This certain scholarly field, as an academic
discipline and as a practical application to engineering problems, is the
quintessential success story for why raw intellectualism delivers on its
promises. To say that this field found success with even the more prudishly
pragmatic elements of society is to deprive mathematics of its many more
splendid laurels that intend to pay dividends commensurate with the prosperity
of humanity. Indeed, it is our primary intellectual beast of burden on which the
modern world rests.

And to say that the mathematical edifice bequeathed to us by the historical
process captured our effervescent spirit is to mitigate our immodest revel in
the art. Surely, we have been enraptured by this craft and the practitioners
thereof have experienced a lofty elevation in status among the common populace.
This is a very interesting development for a field known to be arcane and
relatively inaccessible to the wider audience. One imagines it is this very
unapproachability that contributes the consensus of our age and conclusively
regards math as a divinely inspired creation.

And it is this consensus, that mathematics has evaded the perdition that haunts
humanity since the fall; that this craft offers us a glimpse at the heavenly
realms that elude our vision; and that there is no incremental historical
development to speak of when discussing this body work, as such a divine
creation would not allow itself to be mended piece-wise. Yes it is this
consensus that I wish to disabuse.

* Why the Venom?
** A Frank Tangent
The idea is that it has been in vogue of academics to fashion literature for the
purposes of excoriating subjects or concepts that they wish to diminish. The
intent is to deface the public's appreciation of some established thought for
political purposes. This is an ensconced tradition of academic life and the
prime vehicle by which public intellectuals affect change in their respective
societies.

I pray that this not come as a revelation to any. As a self-proclaimed private
intellectual, I am bolstered by power that ideas can have once championed and
wielded for the progressive transformation of society. If you believe a fanciful
concoction contrived for whatever purposes this author has envisioned, let God
be merciful to thee for through your reigns does the spirit of the enlightenment
has ventured yet to flow. I pray what prospective castigation visits you prove
exhaustive in peeling the scales from your eyes.

** Deconstructing a God
Thus, what becomes of the method? The guise of presenting a vitriolic tonic as
literature or _theory_ has a vast volume of written word under its purview. I
invoke deconstruction in an article purporting to render a sacred theme into its
constituent functional parts. In the great drama of history and by the vanguards
that hold the traditions that haunt us, does that not render this author a
devil?

I, ever the diplomat, seek to humor those that are satisfied with ejecting some
truculent snarl word my way. This author unequivocally realizes the appreciate
value of realms of thought and wishes all intellectual endeavors a appreciable
longevity. Naturally, some of these endeavors will have an acidic reality to
them. I want to discuss at length this patina that envelops certain theories as
they are rendered caustic by design. And is lead to wonder what this excoriating
surface is meant to make contact with; and what is the ultimate end of these
objects of inquiry if not to kill all that is sacred.

That will have to wait for another time however.

** A Glorious Hunt Await...
No one laments more how scarce temporal resources are than this author.
Unfortunately, I feel I have exhausted what verbal devices dictate on this
matter. Suffice the warrant that topic, deconstruction, merits a future look.
And expect me, dear idle reader, that this author will hold back on his hunt. I
maintain that deconstruction is an amoral production of academia yet often we
find in perdition those that utilize it; that is no coincidence.

In the future, this author, armed but with the most humble of instruments, will
render a show for thee moralist. The deconstructors will be sorted and made
intellectual examples. Yes, dear reader; they have tread less than lightly over
this author's sanctified tradition as well. And may the devil visit me himself
if I did not apologetically admit to the seduction by the vindictive spirit of
irredentism. To this predilection, I humbly witness.

May the lid remains securely fastened on that enterprise for the time being.

* Pedagogical and Discursive Realities - What is Math?
The extent permitted by the cognizance that most of our citizenry has in respect
to math is circumscribed by their grade school experience. The math curriculum
of today has gone through an elaborate gauntlet of vicissitudes. Current
mathematical pedagogy can best be understood as constituted by a series of
fractious schools of thought that purport to thoroughly address the concerns of
each other and evince themselves as possessing the correct approach to pedagogy.
Iterate upon this scenario for decades and we arrive at our current curriculum.

** Political Churn
Far be it from me, someone of particular nondescript affiliation with those
formal pedagogical institutions to comment on the nature of the iterative
political process. I do not extend but embrace my lapses in knowledge pertaining
to the exercise of the political environment constituting the esconcement of the
pedagogical nature of mathematics. All this princely word-mince to imply that
the context of teaching mathematics is as political as whatever incumbent
enterprises that mathematicians engage in therein math proper.

That said, I pray deft ears resist the erosive temptation to deny this field its
Apollo consensus.


* Mathematics as Prophetic Revelation

* The Holy Sacraments of Mathematics
** Sacred Logic
** Apotheosis of Symbols
** Mathematics as a Social Practice
** Mathematics as a Teleological Undertaking
** The Sublime Truth in Mathematics
** Mathematics's Expansive Metaphysical Empire
** Semiotics of Another Holy Priesthood
** Deconstructing the Sacraments
** Logic as Cause and Effect
